create table category (id integer not null auto_increment, name varchar(30) not null, primary key (id))
create table ebook (id integer not null auto_increment, mime varchar(100), author varchar(120), filename varchar(200) not null, keywords varchar(120), title varchar(80) not null, year integer, category_id integer, language_id integer, user_id integer, primary key (id))
create table language (id integer not null auto_increment, name varchar(30) not null, primary key (id))
create table user (id integer not null auto_increment, first_name varchar(30) not null, last_name varchar(30) not null, password varchar(255) not null, role varchar(30) not null, username varchar(10) not null, category_id integer, primary key (id))
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username)
alter table ebook add constraint FK20h6f5725k4jllfjypi3n5y5e foreign key (category_id) references category (id)
alter table ebook add constraint FKngf1c1fi0fkof53fn5dg8id8l foreign key (language_id) references language (id)
alter table ebook add constraint FKg9qgrgv21doj1cphfl563j4ue foreign key (user_id) references user (id)
alter table user add constraint FKrfbnkwm509b3phkmoyelw86el foreign key (category_id) references category (id)
